import React from 'react';
import Nav from '../components/Nav';
import Footer from '../components/Footer';

const Terms: React.FC = () => {
  return (
    <div className="bg-mitosite-beige min-h-screen">
      <Nav />
      <div className="container mx-auto px-6 py-16 ">
        <h1 className="text-4xl font-bold text-mitosite-beige-dark mb-8 font-cardo">Terms of Service</h1>
        
        <div className="prose prose-lg max-w-none text-mitosite-beige-dark font-josefin">
          
          <p className="mb-1"><strong>Last Updated:</strong> June 30, 2025</p>
          
          <p className="mb-6">PLEASE READ THESE TERMS CAREFULLY. THEY GOVERN YOUR USE OF THE WEBSITE LOCATED AT MITOSITE.AI (THE "SITE") AND THE SERVICES OFFERED THEREIN (THE "SERVICES"). BY ACCESSING OR USING THE SITE OR SERVICES, YOU AGREE TO BE LEGALLY BOUND BY THESE TERMS AND CONDITIONS (THE "TERMS"). IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE SITE OR SERVICES.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">1. Overview of Services</h2>
          <p>Mitosite AI helps software companies create and continuously update their landing pages using artificial intelligence. Our Services include the automated generation of web content, designs, and assets based on inputs provided by users and their public-facing or private repositories.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">2. Registration and Account Responsibility</h2>
          <p>To use certain features of the Services, you may be required to register for an account. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">3. Ownership and License of Generated Assets</h2>
          <p>All code, content, or assets generated through Mitosite AI are created specifically for your company, based on the information you provide. You own all intellectual property rights in the final deliverables generated via your account under a paid subscription.</p>
          <p>Mitosite AI retains no ownership of your deliverables. However, you grant Mitosite AI a limited license to use such materials solely to operate and improve the Services, and to comply with legal obligations.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">4. Disclaimer of Responsibility for Outputs</h2>
          <p>The content and code generated by Mitosite AI are based on automated systems using models trained on public and user-provided data. Mitosite AI makes no guarantees regarding the quality, accuracy, accessibility, or effectiveness of such outputs. YOU ARE SOLELY RESPONSIBLE FOR REVIEWING, TESTING, AND APPROVING ANY CODE OR CONTENT PRIOR TO DEPLOYMENT.</p>
          <p>If any errors, bugs, or legal issues arise from the use of generated content or from enabling automatic updates, Mitosite AI shall not be held liable for any resulting consequences.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">5. Automatic Site Updates and User Consent</h2>
          <p>By opting into Mitosite AI's automated update feature, you acknowledge and accept the risks involved. You are responsible for verifying all changes prior to or following deployment. You may disable automatic updates at any time via your account settings.</p>
          <p>Mitosite AI is not liable for business, financial, reputational, or legal damages arising from any update approved or published automatically on your behalf.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">6. Fees and Subscriptions</h2>
          <p>Mitosite AI offers both free and paid plans. Subscriptions renew automatically unless canceled prior to the next billing cycle. All fees are non-refundable except as required by law. You are responsible for any applicable taxes.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">7. Acceptable Use</h2>
          <p>You agree not to use Mitosite AI to:</p>
          <ul className="list-disc pl-6 mb-6">
            <li>Violate any laws or regulations</li>
            <li>Infringe on intellectual property rights</li>
            <li>Generate malicious, harmful, or illegal content</li>
            <li>Attempt unauthorized access to the Site or Services</li>
            <li>Resell or sublicense the Services without written permission</li>
          </ul>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">8. Third-Party Content and Integrations</h2>
          <p>Mitosite AI may integrate with third-party services such as GitHub. Your use of third-party services is governed by their own terms and privacy policies. Mitosite AI is not responsible for the availability, content, or practices of these third parties.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">9. Intellectual Property</h2>
          <p>All rights, title, and interest in the Mitosite AI platform—including the underlying software, UI/UX, models, and branding—remain the exclusive property of Monarch Park Corp (our parent company). Nothing in these Terms grants you any license to our trademarks or proprietary technology beyond what is required for using the Services.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">10. Termination</h2>
          <p>We may suspend or terminate your access to the Services at our sole discretion, without notice, for conduct that violates these Terms or is otherwise harmful to us or other users. Upon termination, your rights to access or use the Service will immediately cease.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">11. Disclaimers</h2>
          <p>THE SERVICES AND ALL CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. MITOSITE AI DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">12. Limitation of Liability</h2>
          <p>IN NO EVENT WILL MITOSITE AI BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES. OUR AGGREGATE LIABILITY FOR DIRECT DAMAGES SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO MITOSITE AI IN THE SIX (6) MONTHS PRIOR TO THE EVENT GIVING RISE TO THE CLAIM.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">13. Indemnification</h2>
          <p>You agree to indemnify, defend, and hold harmless Mitosite AI, its affiliates, officers, directors, and employees from any claims, losses, damages, liabilities, or costs (including legal fees) arising from your use of the Services or violation of these Terms.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">14. Governing Law and Dispute Resolution</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware. Any disputes will be resolved through binding arbitration in San Francisco, California, except where prohibited by law.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">15. Updates to These Terms</h2>
          <p>We may update these Terms from time to time. If we do, we will notify you by posting the updated Terms on our website or via email. Continued use of the Services after such changes constitutes your acceptance of the new Terms.</p>
          
          <hr className="my-6 border-mitosite-beige-mid" />
          
          <h2 className="text-2xl font-bold mt-8 mb-4 font-cardo">16. Contact Information</h2>
          <p>If you have any questions about these Terms or the Services, please contact us at:
          <br /><a href="mailto:support@mitosite.ai" className="text-mitosite-beige-dark underline hover:text-mitosite-green">support@mitosite.ai</a></p>
        
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Terms; 