import React from 'react';

const Companies: React.FC = () => {
  return (
    <div className="flex items-center justify-between pl-6 border-b border-mitosite-beige-dark bg-mitosite-beige-dark">
      <div className="font-cardo text-mitosite-beige text-xl">
        Trusted by startups. Generated by AI, overviewed by human design professionals.
      </div>
      
      <div className="flex ">
        {/* Company logos would go here - using placeholder divs for now */}
        {[1, 2, 3, 4, 5].map((_, index) => (
          <div 
            key={index}
            className="w-32 h-32 bg-mitosite-beige flex items-center justify-center border-r border-mitosite-beige-dark"
          >
            <span className="text-mitosite-beige-dark">Logo {index + 1}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Companies;
